classifier:
  train_data_dir: $WORK/vision_datasets/imagenette64
  test_data_dir: null
  class_list:
    - english_springer
    - french_horn
  num_epochs: 20
  lr: 1e-3
  train_split: 0.8
  max_allowed_samples_per_class: 1024
  max_allowed_samples_per_class_test: 1024
  n_train_samples_per_class: 1024
  n_test_samples_per_class: 1024
  train_augmentations: null
  batch_size: 64
  device: cuda:5
  n_runs: 10
  n_props_train: 10
  resample_train_subset: false
  resample_test_subset: false
  reset_model_random_seed: false
  eval_epoch_interval: 10
  early_stopping_patience: 100
  verbose: false
  save_dir: results/classifier
  save_name: classifier
  model_save_dir: null
  save_interval: 1

  criterion: MSELoss

  model:
    name: LinearMulticlassClassifier

    LinearMulticlassClassifier_kwargs: {}

    TwoLayerMulticlassClassifier_kwargs:
      hidden_dim: 64

    LinearBinaryClassifier_kwargs:
      output_logit: false

    TwoLayerBinaryClassifier_kwargs:
      hidden_dim: 64
      output_logit: false

    ResNet64_kwargs:
      pretrained: true
      output_logit: false

  optimizer:
    name: SGD

    SGD_kwargs:
      momentum: 0
      dampening: 0
      weight_decay: 0
      nesterov: false

    Adam_kwargs:
      betas: [0.9, 0.999]
      eps: 1e-8

    AdamW_kwargs:
      weight_decay: 1e-3
      betas: [0.9, 0.999]
      eps: 1e-8

  scheduler:
    name: CosineAnnealingLR

    StepLR_kwargs:
      step_size: 10
      gamma: 0.1

    CosineAnnealingLR_kwargs:
      T_max: 200
      eta_min: 1e-4

    CosineAnnealingWarmRestarts_kwargs:
      T_0: 200
      T_mult: 1
      eta_min: 1e-4

  dataloader_kwargs:
    shuffle: true
    num_workers: 24
    persistent_workers: true
    pin_memory: true
    make_prefetcher: true