classifier:
  class_list:
    - english_springer
    - french_horn
  criterion: MSELoss
  num_epochs: 20
  lr: 1e-3
  train_split: 0.8
  max_allowed_samples_per_class: 1000
  batch_size: 64
  device: cuda:5
  prop_samples_train: 1.0
  n_runs: 10
  n_props_train: 10
  reset_model_random_seed: false
  verbose: false
  save_dir: results/classifier
  save_name: null

  optimizer:
    method: SGD

    SGD_kwargs:
      momentum: 0
      dampening: 0
      weight_decay: 0
      nesterov: false

    Adam_kwargs:
      betas: [0.9, 0.999]
      eps: 1e-8

    AdamW_kwargs:
      weight_decay: 1e-3
      betas: [0.9, 0.999]
      eps: 1e-8

  scheduler:
    method: StepLR

    StepLR_kwargs:
      step_size: 10
      gamma: 0.1
