classifier:
  train_data_dir: $WORK/vision_datasets/imagenette64
  test_data_dir: null
  class_list:
    - english_springer
    - french_horn
  num_epochs: 20
  lr: 1e-3
  train_split: 0.8
  max_allowed_samples_per_class: 1024
  batch_size: 64
  device: cuda:5
  n_runs: 10
  n_props_train: 10
  use_augmentations: false
  reset_model_random_seed: false
  verbose: false
  save_dir: results/classifier
  save_name: classifier

  criterion: MSELoss

  model:
    name: LinearMulticlassClassifier

    LinearMulticlassClassifier_kwargs: {}

    TwoLayerMulticlassClassifier_kwargs:
      hidden_dim: 64

    LinearBinaryClassifier_kwargs:
      output_logit: false

    TwoLayerBinaryClassifier_kwargs:
      hidden_dim: 64
      output_logit: false
      
  optimizer:
    name: SGD

    SGD_kwargs:
      momentum: 0
      dampening: 0
      weight_decay: 0
      nesterov: false

    Adam_kwargs:
      betas: [0.9, 0.999]
      eps: 1e-8

    AdamW_kwargs:
      weight_decay: 1e-3
      betas: [0.9, 0.999]
      eps: 1e-8

  scheduler:
    name: StepLR

    StepLR_kwargs:
      step_size: 10
      gamma: 0.1

    CosineAnnealingLR_kwargs:
      T_max: 200
      eta_min: 1e-4
