classifier:
  class_list:
    - english_springer
    - french_horn
  criterion: MSELoss
  num_epochs: 20
  lr: 1e-3
  train_split: 0.8
  batch_size: 64
  device: cuda:0
  rseed: 99

  optimizer:
    method: SGD

    SGD_kwargs:
      momentum: 0
      dampening: 0
      weight_decay: 0
      nesterov: false

    Adam_kwargs:
      betas: [0.9, 0.999]
      eps: 1e-8

    AdamW_kwargs:
      weight_decay: 1e-3
      betas: [0.9, 0.999]
      eps: 1e-8

  scheduler:
    method: StepLR

    StepLR_kwargs:
      step_size: 10
      gamma: 0.1
