defaults:
  - _self_
  - diffusion
  - gmm
  - dataset
  - experiment
  # - override hydra/job_logging: disabled 
  - override hydra/hydra_logging: disabled 

hydra:
  output_subdir: null
  run:
    dir: logs

rseed: 0