# directory containing files used for training data
data_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/"

cifar10:
  real_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/cifar10/"
  diffusion_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/diffusion_cifar10/"
  gmm_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/gmm_cifar10/"

imagenet:
  real_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/imagenet/"
  diffusion_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/diffusion_imagenet/"
  gmm_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/gmm_imagenet/"

