gmm:
  n_components: 1
  data_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/cifar10"
  dataset_name: cifar10
  covariance_type: full
  class_list:
    - bird
    - cat
    - dog
  save_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/gmm_cifar10/unknown"
  verbose: true