gmm:
  n_components: 1
  datapath: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/cifar10"
  dataset_name: cifar10
  target_class: null
  custom_transform: null
  batch_size: 32
  n_samples_fit: 1024
  n_samples_generate: 1024
  save_dir: "/stor/work/AMDG_Gilpin_Summer2024/vision_datasets/gmm_cifar10/unknown"