gmm:
  n_components: 1
  data_dir: null
  dataset_name: null
  covariance_type: full
  batch_size: 64
  sample_idx: 0
  classes:
    - bird
    - cat
    - dog
  n_samples_fit: 1024
  n_samples_generate: 1024
  save_dir: null
  stats_save_dir: null
  verbose: true